[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_escrow = "7D6qfqnKDM2ktD634e8HMiAbDBMZG8cWARKRbmL8MxLW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ilpr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
